name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Push changes
        run: |
          git config user.name hdi1021
          git config user.email "your-email@example.com"
          git add .
          git commit -m "generated"
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/hdi1021/hdi1021.git HEAD:main
