name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # 매일 03:00 JST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push if Changes
        run: |
          git config --global user.name "hdi1021"
          git config --global user.email "your-email@example.com"

          git add .
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "generated"
            git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/hdi1021/hdi1021.git HEAD:main
          fi
